// This file is generated by `flutterfire configure`.
// Run `flutterfire configure` in the mobile/ directory to populate it with
// your Firebase project's values for each supported platform.
//
// Instructions:
//   1. Install the FlutterFire CLI: `dart pub global activate flutterfire_cli`
//   2. From the mobile/ directory run: `flutterfire configure`
//   3. Select your Firebase project and target platforms (iOS, Android).
//   4. This file will be overwritten with real values.
//
// Until this file is generated, Firebase initialization is skipped and the app
// runs in "no-Firebase" mode (auth features will not work).

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform;

/// Whether Firebase has been configured for this build.
///
/// Returns false if this file is still the placeholder. Feature code must
/// check this before calling Firebase APIs.
bool get isFirebaseConfigured => true;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ── PLACEHOLDER VALUES — replace by running `flutterfire configure` ────────

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh3o4n32HSgpAY20OUfsoI3zaZ1X00FkE',
    appId: '1:5392643534:android:70594aee6b76dd7b49679f',
    messagingSenderId: '5392643534',
    projectId: 'arkmask',
    storageBucket: 'arkmask.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUQgF5at4c8K1Bb5bKS9sdu3JndQhgjCQ',
    appId: '1:5392643534:ios:f7d7cace267f999a49679f',
    messagingSenderId: '5392643534',
    projectId: 'arkmask',
    storageBucket: 'arkmask.firebasestorage.app',
    iosBundleId: 'com.arkmask.arkMask',
  );

}